// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SmartHomeApplicationAPI.Infrastructure;

#nullable disable

namespace SmartHomeApplicationAPI.Migrations
{
    [DbContext(typeof(SmartHomeDbContext))]
    [Migration("20261008083140_AddPresetsAndDevicePresetForeignKey")]
    partial class AddPresetsAndDevicePresetForeignKey
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SmartHomeApplicationAPI.Infrastructure.Models.DayAheadPrice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsPredicted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_predicted");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("price");

                    b.Property<string>("PriceArea")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("price_area");

                    b.Property<DateTime>("Time")
                        .HasColumnType("timestamp(0) without time zone")
                        .HasColumnName("time");

                    b.HasKey("Id")
                        .HasName("day_ahead_price_pkey");

                    b.ToTable("day_ahead_price", (string)null);
                });

            modelBuilder.Entity("SmartHomeApplicationAPI.Infrastructure.Models.Devices", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("category");

                    b.Property<decimal>("ConsumptionInKwh")
                        .HasColumnType("numeric")
                        .HasColumnName("consumption_in_kwh");

                    b.Property<int>("DurationInMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("duration_in_minutes");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("icon");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.Property<int>("PresetId")
                        .HasColumnType("integer")
                        .HasColumnName("preset_id");

                    b.HasKey("Id");

                    b.HasIndex("PresetId");

                    b.ToTable("devices");
                });

            modelBuilder.Entity("SmartHomeApplicationAPI.Infrastructure.Models.Presets", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("ConsumptionInKwh")
                        .HasColumnType("numeric")
                        .HasColumnName("consumption_in_kwh");

                    b.Property<int>("DurationInMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("duration_in_minutes");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("presets");
                });

            modelBuilder.Entity("SmartHomeApplicationAPI.Infrastructure.Models.Schedules", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DeviceId")
                        .HasColumnType("integer")
                        .HasColumnName("device_id");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_time");

                    b.Property<decimal>("EstimatedCo2Emissions")
                        .HasColumnType("numeric")
                        .HasColumnName("estimated_co2_emissions_in_percent");

                    b.Property<decimal>("EstimatedPrice")
                        .HasColumnType("money")
                        .HasColumnName("estimated_price_in_kroner");

                    b.Property<int?>("NextScheduleId")
                        .HasColumnType("integer")
                        .HasColumnName("next_schedule_id");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_time");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.HasIndex("NextScheduleId");

                    b.HasIndex("UserId");

                    b.ToTable("schedules");
                });

            modelBuilder.Entity("SmartHomeApplicationAPI.Infrastructure.Models.Users", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("password");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("role")
                        .HasComment("defaults to user. has to be upgraded manually");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.ToTable("users");
                });

            modelBuilder.Entity("SmartHomeApplicationAPI.Infrastructure.Models.Devices", b =>
                {
                    b.HasOne("SmartHomeApplicationAPI.Infrastructure.Models.Presets", "Preset")
                        .WithMany("Devices")
                        .HasForeignKey("PresetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Preset");
                });

            modelBuilder.Entity("SmartHomeApplicationAPI.Infrastructure.Models.Schedules", b =>
                {
                    b.HasOne("SmartHomeApplicationAPI.Infrastructure.Models.Devices", "Device")
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartHomeApplicationAPI.Infrastructure.Models.Schedules", "NextSchedule")
                        .WithMany()
                        .HasForeignKey("NextScheduleId");

                    b.HasOne("SmartHomeApplicationAPI.Infrastructure.Models.Users", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");

                    b.Navigation("NextSchedule");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartHomeApplicationAPI.Infrastructure.Models.Presets", b =>
                {
                    b.Navigation("Devices");
                });
#pragma warning restore 612, 618
        }
    }
}
